export const PRODUCT_CONTENT = {
  'btc-x-ea-mt5': {
    name: 'BTC MLT',
    comingSoon: false,
    desc: 'BTC MLT is an Expert Advisor (EA) for automated trading on BTCUSD, built for the MetaTrader 5 (MT5) platform. It follows a rule-based approach: it reads market conditions through technical filters, opens positions when its conditions are met, and manages those positions with predefined risk controls.',
    whyTitle: 'Why Use BTC MLT?',
    why: [
      'Rule-based entries remove emotional, manual trading decisions.',
      'Trend and volatility filters keep entries structured in fast crypto markets.',
      'Full automation across the always-open BTCUSD market.',
      'Built-in risk framework with stops on every position.',
    ],
    features: [
      'Advanced trend and volatility filters using ADX and ATR for structured entries.',
      'Dynamic lot scaling — position sizes adjust to the account balance.',
      'Multi-position trade handling across trending phases.',
      'Trailing stop profit protection that secures gains dynamically.',
      '24/7 crypto compatibility for always-open markets.',
    ],
    usage: [
      'Install the EA file into the MT5 Experts folder and restart the terminal.',
      'Attach BTC MLT to a BTCUSD M15 or H1 chart and allow automated trading.',
      'Start with conservative settings and validate on a demo account first.',
      'Never trade with funds you cannot afford to lose.',
    ],
    faqs: [
      { q: 'Which platform does BTC MLT need?', a: 'MetaTrader 5 (MT5) with a BTCUSD symbol.' },
      { q: 'What is the minimum deposit?', a: 'The recommended minimum deposit is $100.' },
      { q: 'Does it trade automatically?', a: 'Yes. Once attached and enabled, it opens and manages positions by its rules.' },
      { q: 'Is any trading system risk-free?', a: 'No. Always test on demo first and never trade with funds you cannot afford to lose.' },
    ],
    specs: [
      { k: 'Trading platform', v: 'MetaTrader 5 (MT5)' },
      { k: 'Minimum / recommended deposit', v: '$100' },
      { k: 'Timeframes', v: 'M15 / H1' },
      { k: 'Instruments', v: 'BTCUSD (Bitcoin)' },
      { k: 'Setup files', v: 'Included' },
      { k: 'Licence type', v: 'Single account, digital delivery' },
      { k: 'Delivery', v: 'Instant digital delivery + installation guidance' },
    ],
  },
  'galaxy-prop-firm-ea-mt5': {
    name: 'Currency Bot Coins',
    comingSoon: false,
    desc: 'Currency Bot Coins MT5 is designed to automate trading strategies on the MT5 platform, catering particularly to the needs and constraints of proprietary trading firms. These firms usually provide capital to traders in exchange for a share of the profits generated. The EA aims to maximize profitability while adhering to the risk management guidelines typically imposed by prop firms.',
    whyTitle: 'Why Use Currency Bot Coins?',
    why: [
      'High degree of customization to match different prop-firm strategies and risk rules.',
      'Stringent risk management features that help meet daily and total drawdown requirements.',
      'Full automation with 24/5 market monitoring without constant human oversight.',
      'Built for MT5: multi-asset trading, advanced charting and superior backtesting.',
    ],
    features: [
      'Multi-currency system across 8 Forex pairs from a single EA.',
      'Automatic money management that sizes positions to the account and risk framework.',
      'Spread protection that filters entries when market spread is unfavourable.',
      'Drawdown protection with an automatic mechanism that closes positions at the threshold.',
      'Flexible lot control: minimum, maximum, fixed and automatic position sizing.',
      'Configurable Take Profit and Stop Loss multipliers.',
      'Trailing-stop profit protection after the required movement.',
      'Prop-firm ready controls for challenge and funded accounts.',
    ],
    usage: [
      'Install the EA file into the MT5 Experts folder and restart the terminal.',
      'Attach Currency Bot Coins to an H1 chart and allow automated trading.',
      'Configure risk, lot limits, spread filter and drawdown threshold first.',
      'Validate everything on a demo or challenge account before going funded.',
    ],
    faqs: [
      { q: 'Which currency pairs does Currency Bot Coins trade?', a: 'NZDCAD, EURCAD, USDCHF, AUDUSD, CADJPY, EURCHF, EURJPY and GBPNZD on H1.' },
      { q: 'What is the minimum deposit?', a: 'The recommended minimum deposit is $200, though prop-firm requirements may vary.' },
      { q: 'Does it have drawdown protection?', a: 'Yes. It closes positions automatically when the configured maximum drawdown condition is reached.' },
      { q: 'Can individuals use it outside prop firms?', a: 'Yes. Individual traders can use it on personal accounts with the same risk controls.' },
      { q: 'Is any trading system risk-free?', a: 'No. Always test on demo first and never trade with funds you cannot afford to lose.' },
    ],
    specs: [
      { k: 'Trading platform', v: 'MetaTrader 5 (MT5)' },
      { k: 'Minimum / recommended deposit', v: '$200' },
      { k: 'Timeframes', v: 'H1 (60 minute chart)' },
      { k: 'Currency pairs', v: 'NZDCAD, EURCAD, USDCHF, AUDUSD, CADJPY, EURCHF, EURJPY, GBPNZD' },
      { k: 'Setup files', v: 'Included' },
      { k: 'Licence type', v: 'Single account, digital delivery' },
      { k: 'Delivery', v: 'Instant digital delivery + installation guidance' },
    ],
  },
  'ict-silver-bullet-ea-mt4': {
    name: 'Silver',
    comingSoon: true,
    desc: 'Silver is the upcoming release from BTCMLTAI and is currently in final testing. It is planned as a focused Expert Advisor with a disciplined, low-frequency trading style, structured entries, and predefined risk controls on every position.',
    whyTitle: 'Why Watch Silver?',
    why: [
      'A disciplined system designed for controlled exposure.',
      'Structured entries with predefined risk controls.',
      'Full BTCMLTAI digital delivery with installation guidance at launch.',
    ],
    statusNote: 'Silver is not available for order yet. Price and final specifications will be announced at launch. Share your details through Notify Me and our team will contact you within 2 to 3 hours of launch updates.',
    usage: null,
    faqs: [
      { q: 'When does Silver launch?', a: 'Final testing is underway. Join the early list to be notified first.' },
      { q: 'What will the price be?', a: 'Pricing will be announced at launch.' },
      { q: 'How will I get notified?', a: 'Use Notify Me on this page with your name, email and phone number.' },
    ],
    specs: [
      { k: 'Status', v: 'Coming soon — in final testing' },
      { k: 'Platform', v: 'To be announced at launch' },
      { k: 'Instruments', v: 'To be announced at launch' },
      { k: 'Delivery', v: 'Digital delivery at launch' },
    ],
  },
};

export const PRODUCT_ORDER = ['btc-x-ea-mt5', 'galaxy-prop-firm-ea-mt5', 'ict-silver-bullet-ea-mt4'];
